In [1]:
import fastf1
import pandas as pd
fastf1.Cache.enable_cache('D:\\Programming\\Python\\AI\\F1 Fantasy\\cache')

In [2]:
events = fastf1.get_events_remaining()
nextRound = events.iloc[0].RoundNumber-1

In [3]:
round = nextRound-1

# load race session (uses same `round` var you used for qualifying)
session = fastf1.get_session(2026, round, 'R')
session.load(telemetry=False)

laps = session.laps.copy()

# keep only real lap times
laps = laps[laps['LapTime'].notna()]
laps

core           INFO 	Loading data for Hungarian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '11'
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['1', '3', '12', '16', '44', '6', '63', '30', '27', '41', '5', '10', '18', '14', '43', '31', '23', '55', '87', '81', '11', '77']

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 00:55:39.455000,NOR,1,0 days 00:01:31.211000,1.0,1.0,NaT,NaT,NaT,0 days 00:00:32.050000,...,True,McLaren,0 days 00:54:08.019000,NaT,1,2.0,False,,False,False
1,0 days 00:57:05.558000,NOR,1,0 days 00:01:26.103000,2.0,1.0,NaT,NaT,0 days 00:00:29.822000,0 days 00:00:31.728000,...,True,McLaren,0 days 00:55:39.455000,NaT,1,2.0,False,,False,True
2,0 days 00:58:30.865000,NOR,1,0 days 00:01:25.307000,3.0,1.0,NaT,NaT,0 days 00:00:29.629000,0 days 00:00:31.235000,...,True,McLaren,0 days 00:57:05.558000,NaT,1,2.0,False,,False,True
3,0 days 00:59:56.049000,NOR,1,0 days 00:01:25.184000,4.0,1.0,NaT,NaT,0 days 00:00:29.692000,0 days 00:00:31.177000,...,True,McLaren,0 days 00:58:30.865000,NaT,1,2.0,False,,False,True
4,0 days 01:01:21.272000,NOR,1,0 days 00:01:25.223000,5.0,1.0,NaT,NaT,0 days 00:00:29.832000,0 days 00:00:30.984000,...,True,McLaren,0 days 00:59:56.049000,NaT,1,2.0,False,,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1426,0 days 02:29:04.832000,BEA,87,0 days 00:01:27.035000,64.0,3.0,NaT,NaT,0 days 00:00:29.816000,0 days 00:00:32.174000,...,True,Haas F1 Team,0 days 02:27:37.797000,NaT,1,17.0,False,,False,True
1427,0 days 02:30:32.120000,BEA,87,0 days 00:01:27.288000,65.0,3.0,NaT,NaT,0 days 00:00:29.862000,0 days 00:00:32.295000,...,True,Haas F1 Team,0 days 02:29:04.832000,NaT,1,17.0,False,,False,True
1428,0 days 02:31:59.762000,BEA,87,0 days 00:01:27.642000,66.0,3.0,NaT,NaT,0 days 00:00:29.974000,0 days 00:00:32.511000,...,True,Haas F1 Team,0 days 02:30:32.120000,NaT,1,17.0,False,,False,True
1429,0 days 02:33:27.662000,BEA,87,0 days 00:01:27.900000,67.0,3.0,NaT,NaT,0 days 00:00:30.176000,0 days 00:00:32.536000,...,True,Haas F1 Team,0 days 02:31:59.762000,NaT,1,17.0,False,,False,True
1430,0 days 02:34:56.622000,BEA,87,0 days 00:01:28.960000,68.0,3.0,NaT,NaT,0 days 00:00:30.338000,0 days 00:00:33.073000,...,True,Haas F1 Team,0 days 02:33:27.662000,NaT,1,17.0,False,,False,True

In [4]:
laps = session.laps.copy()
laps = laps.pick_wo_box().pick_not_deleted().pick_accurate().pick_track_status('1')
laps[laps['Driver'] == "PIA"]

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
1308,0 days 00:57:04.590000,PIA,81,0 days 00:01:26.060000,2.0,1.0,NaT,NaT,0 days 00:00:30.060000,0 days 00:00:31.643000,...,True,McLaren,0 days 00:55:38.530000,NaT,1,1.0,False,,False,True
1309,0 days 00:58:29.862000,PIA,81,0 days 00:01:25.272000,3.0,1.0,NaT,NaT,0 days 00:00:29.724000,0 days 00:00:31.241000,...,True,McLaren,0 days 00:57:04.590000,NaT,1,1.0,False,,False,True
1310,0 days 00:59:55.016000,PIA,81,0 days 00:01:25.154000,4.0,1.0,NaT,NaT,0 days 00:00:29.886000,0 days 00:00:30.996000,...,True,McLaren,0 days 00:58:29.862000,NaT,1,1.0,False,,False,True
1311,0 days 01:01:20.111000,PIA,81,0 days 00:01:25.095000,5.0,1.0,NaT,NaT,0 days 00:00:29.943000,0 days 00:00:30.799000,...,True,McLaren,0 days 00:59:55.016000,NaT,1,1.0,False,,False,True
1312,0 days 01:02:45.141000,PIA,81,0 days 00:01:25.030000,6.0,1.0,NaT,NaT,0 days 00:00:29.906000,0 days 00:00:30.915000,...,True,McLaren,0 days 01:01:20.111000,NaT,1,1.0,False,,False,True
1313,0 days 01:04:09.981000,PIA,81,0 days 00:01:24.840000,7.0,1.0,NaT,NaT,0 days 00:00:29.709000,0 days 00:00:30.842000,...,True,McLaren,0 days 01:02:45.141000,NaT,1,1.0,False,,False,True
1314,0 days 01:05:35.320000,PIA,81,0 days 00:01:25.339000,8.0,1.0,NaT,NaT,0 days 00:00:29.871000,0 days 00:00:31.214000,...,True,McLaren,0 days 01:04:09.981000,NaT,1,1.0,False,,False,True
1315,0 days 01:07:00.709000,PIA,81,0 days 00:01:25.389000,9.0,1.0,NaT,NaT,0 days 00:00:29.950000,0 days 00:00:31.135000,...,True,McLaren,0 days 01:05:35.320000,NaT,1,1.0,False,,False,True
1316,0 days 01:08:26.375000,PIA,81,0 days 00:01:25.666000,10.0,1.0,NaT,NaT,0 days 00:00:30.070000,0 days 00:00:31.273000,...,True,McLaren,0 days 01:07:00.709000,NaT,1,1.0,False,,False,True
1317,0 days 01:09:51.793000,PIA,81,0 days 00:01:25.418000,11.0,1.0,NaT,NaT,0 days 00:00:29.889000,0 days 00:00:31.287000,...,True,McLaren,0 days 01:08:26.375000,NaT,1,1.0,False,,False,True
1318,0 days 01:11:17.591000,PIA,81,0 days 00:01:25.798000,12.0,1.0,NaT,NaT,0 days 00:00:30.109000,0 days 00:00:31.361000,...,True,McLaren,0 days 01:09:51.793000,NaT,1,1.0,False,,False,True
1319,0 days 01:12:43.516000,PIA,81,0 days 00:01:25.925000,13.0,1.0,NaT,NaT,0 days 00:00:30.154000,0 days 00:00:31.437000,...,True,McLaren,0 days 01:11:17.591000,NaT,1,1.0,False,,False,True
1320,0 days 01:14:09.197000,PIA,81,0 days 00:01:25.681000,14.0,1.0,NaT,NaT,0 days 00:00:29.975000,0 days 00:00:31.288000,...,True,McLaren,0 days 01:12:43.516000,NaT,1,1.0,False,,False,True
1321,0 days 01:15:34.840000,PIA,81,0 days 00:01:25.643000,15.0,1.0,NaT,NaT,0 days 00:00:29.977000,0 days 00:00:31.206000,...,True,McLaren,0 days 01:14:09.197000,NaT,1,1.0,False,,False,True
1324,0 days 01:20:14.559000,PIA,81,0 days 00:01:26.476000,18.0,2.0,NaT,NaT,0 days 00:00:29.784000,0 days 00:00:32.120000,...,True,McLaren,0 days 01:18:48.083000,NaT,1,3.0,False,,False,True
1325,0 days 01:21:39.402000,PIA,81,0 days 00:01:24.843000,19.0,2.0,NaT,NaT,0 days 00:00:29.894000,0 days 00:00:31.004000,...,True,McLaren,0 days 01:20:14.559000,NaT,1,2.0,False,,False,True
1326,0 days 01:23:03.909000,PIA,81,0 days 00:01:24.507000,20.0,2.0,NaT,NaT,0 days 00:00:29.671000,0 days 00:00:30.871000,...,True,McLaren,0 days 01:21:39.402000,NaT,1,2.0,False,,False,True
1327,0 days 01:24:28.355000,PIA,81,0 days 00:01:24.446000,21.0,2.0,NaT,NaT,0 days 00:00:29.588000,0 days 00:00:30.799000,...,True,McLaren,0 days 01:23:03.909000,NaT,1,2.0,False,,False,True
1328,0 days 01:25:52.637000,PIA,81,0 days 00:01:24.282000,22.0,2.0,NaT,NaT,0 days 00:00:29.594000,0 days 00:00:30.746000,...,True,McLaren,0 days 01:24:28.355000,NaT,1,2.0,False,,False,True
1329,0 days 01:27:17.115000,PIA,81,0 days 00:01:24.478000,23.0,2.0,NaT,NaT,0 days 00:00:29.726000,0 days 00:00:30.744000,...,True,McLaren,0 days 01:25:52.637000,NaT,1,1.0,False,,False,True
1330,0 days 01:28:41.907000,PIA,81,0 days 00:01:24.792000,24.0,2.0,NaT,NaT,0 days 00:00:29.682000,0 days 00:00:30.855000,...,True,McLaren,0 days 01:27:17.115000,NaT,1,1.0,False,,False,True
1331,0 days 01:30:06.864000,PIA,81,0 days 00:01:24.957000,25.0,2.0,NaT,NaT,0 days 00:00:29.781000,0 days 00:00:31.030000,...,True,McLaren,0 days 01:28:41.907000,NaT,1,1.0,False,,False,True
1332,0 days 01:31:32.269000,PIA,81,0 days 00:01:25.405000,26.0,2.0,NaT,NaT,0 days 00:00:29.921000,0 days 00:00:31.188000,...,True,McLaren,0 days 01:30:06.864000,NaT,1,1.0,False,,False,True
1333,0 days 01:32:57.734000,PIA,81,0 days 00:01:25.465000,27.0,2.0,NaT,NaT,0 days 00:00:30.015000,0 days 00:00:31.119000,...,True,McLaren,0 days 01:31:32.269000,NaT,1,1.0,False,,False,True
1334,0 days 01:34:22.856000,PIA,81,0 days 00:01:25.122000,28.0,2.0,NaT,NaT,0 days 00:00:29.764000,0 days 00:00:31.075000,...,True,McLaren,0 days 01:32:57.734000,NaT,1,1.0,False,,False,True
1335,0 days 01:35:48.688000,PIA,81,0 days 00:01:25.832000,29.0,2.0,NaT,NaT,0 days 00:00:29.798000,0 days 00:00:31.453000,...,True,McLaren,0 days 01:34:22.856000,NaT,1,1.0,False,,False,True
1336,0 days 01:37:14.423000,PIA,81,0 days 00:01:25.735000,30.0,2.0,NaT,NaT,0 days 00:00:29.890000,0 days 00:00:31.298000,...,True,McLaren,0 days 01:35:48.688000,NaT,1,1.0,False,,False,True
1337,0 days 01:38:40.266000,PIA,81,0 days 00:01:25.843000,31.0,2.0,NaT,NaT,0 days 00:00:29.899000,0 days 00:00:31.419000,...,True,McLaren,0 days 01:37:14.423000,NaT,1,1.0,False,,False,True
1338,0 days 01:40:06.097000,PIA,81,0 days 00:01:25.831000,32.0,2.0,NaT,NaT,0 days 00:00:29.876000,0 days 00:00:31.514000,...,True,McLaren,0 days 01:38:40.266000,NaT,1,1.0,False,,False,True
1341,0 days 01:44:42.105000,PIA,81,0 days 00:01:23.896000,35.0,3.0,NaT,NaT,0 days 00:00:29.357000,0 days 00:00:30.737000,...,True,McLaren,0 days 01:43:18.209000,NaT,1,5.0,False,,False,True
1342,0 days 01:46:06.240000,PIA,81,0 days 00:01:24.135000,36.0,3.0,NaT,NaT,0 days 00:00:29.353000,0 days 00:00:30.827000,...,True,McLaren,0 days 01:44:42.105000,NaT,1,5.0,False,,False,True
1343,0 days 01:47:31.746000,PIA,81,0 days 00:01:25.506000,37.0,3.0,NaT,NaT,0 days 00:00:29.467000,0 days 00:00:31.593000,...,True,McLaren,0 days 01:46:06.240000,NaT,1,4.0,False,,False,True
1344,0 days 01:48:58.110000,PIA,81,0 days 00:01:26.364000,38.0,3.0,NaT,NaT,0 days 00:00:31.026000,0 days 00:00:31.507000,...,True,McLaren,0 days 01:47:31.746000,NaT,1,4.0,False,,False,True
1346,0 days 01:51:47.385000,PIA,81,0 days 00:01:24.873000,40.0,3.0,NaT,NaT,0 days 00:00:29.659000,0 days 00:00:31.134000,...,True,McLaren,0 days 01:50:22.512000,NaT,1,4.0,False,,False,True
1347,0 days 01:53:11.770000,PIA,81,0 days 00:01:24.385000,41.0,3.0,NaT,NaT,0 days 00:00:29.639000,0 days 00:00:30.857000,...,True,McLaren,0 days 01:51:47.385000,NaT,1,4.0,False,,False,True
1348,0 days 01:54:36.042000,PIA,81,0 days 00:01:24.272000,42.0,3.0,NaT,NaT,0 days 00:00:29.527000,0 days 00:00:30.759000,...,True,McLaren,0 days 01:53:11.770000,NaT,1,3.0,False,,False,True
1349,0 days 01:56:00.124000,PIA,81,0 days 00:01:24.082000,43.0,3.0,NaT,NaT,0 days 00:00:29.514000,0 days 00:00:30.687000,...,True,McLaren,0 days 01:54:36.042000,NaT,1,3.0,False,,False,True
1350,0 days 01:57:24.532000,PIA,81,0 days 00:01:24.408000,44.0,3.0,NaT,NaT,0 days 00:00:29.658000,0 days 00:00:30.694000,...,True,McLaren,0 days 01:56:00.124000,NaT,1,3.0,False,,False,True
1351,0 days 01:58:48.838000,PIA,81,0 days 00:01:24.306000,45.0,3.0,NaT,NaT,0 days 00:00:29.608000,0 days 00:00:30.704000,...,True,McLaren,0 days 01:57:24.532000,NaT,1,3.0,False,,False,True
1352,0 days 02:00:13.135000,PIA,81,0 days 00:01:24.297000,46.0,3.0,NaT,NaT,0 days 00:00:29.464000,0 days 00:00:30.753000,...,True,McLaren,0 days 01:58:48.838000,NaT,1,3.0,False,,False,True
1353,0 days 02:01:37.384000,PIA,81,0 days 00:01:24.249000,47.0,3.0,NaT,NaT,0 days 00:00:29.382000,0 days 00:00:30.719000,...,True,McLaren,0 days 02:00:13.135000,NaT,1,3.0,False,,False,True
1354,0 days 02:03:02.071000,PIA,81,0 days 00:01:24.687000,48.0,3.0,NaT,NaT,0 days 00:00:29.585000,0 days 00:00:31.019000,...,True,McLaren,0 days 02:01:37.384000,NaT,1,3.0,False,,False,True
1355,0 days 02:04:27.147000,PIA,81,0 days 00:01:25.076000,49.0,3.0,NaT,NaT,0 days 00:00:29.638000,0 days 00:00:30.907000,...,True,McLaren,0 days 02:03:02.071000,NaT,1,3.0,False,,False,True
1357,0 days 02:07:16.256000,PIA,81,0 days 00:01:24.714000,51.0,3.0,NaT,NaT,0 days 00:00:29.620000,0 days 00:00:30.825000,...,True,McLaren,0 days 02:05:51.542000,NaT,1,3.0,False,,False,True
1358,0 days 02:08:40.629000,PIA,81,0 days 00:01:24.373000,52.0,3.0,NaT,NaT,0 days 00:00:29.530000,0 days 00:00:30.739000,...,True,McLaren,0 days 02:07:16.256000,NaT,1,3.0,False,,False,True
1359,0 days 02:10:05.181000,PIA,81,0 days 00:01:24.552000,53.0,3.0,NaT,NaT,0 days 00:00:29.447000,0 days 00:00:30.842000,...,True,McLaren,0 days 02:08:40.629000,NaT,1,3.0,False,,False,True
1360,0 days 02:11:29.781000,PIA,81,0 days 00:01:24.600000,54.0,3.0,NaT,NaT,0 days 00:00:29.479000,0 days 00:00:30.972000,...,True,McLaren,0 days 02:10:05.181000,NaT,1,2.0,False,,False,True
1361,0 days 02:12:54.377000,PIA,81,0 days 00:01:24.596000,55.0,3.0,NaT,NaT,0 days 00:00:29.497000,0 days 00:00:30.874000,...,True,McLaren,0 days 02:11:29.781000,NaT,1,2.0,False,,False,True

In [9]:
round = nextRound-1

session2 = fastf1.get_session(2026, round, 'FP2')
session2.load(telemetry=False)
session2.laps

core           INFO 	Loading data for Hungarian Grand Prix - Practice 2 [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	No lap data for driver 18
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 18)
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['1', '3', '5', '6', '10', '11', '12', '14', '16', '18', '23', '27', '30', '31', '41', '43', '44', '55', '63', '77', '81', '87']

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 00:16:28.410000,NOR,1,NaT,1.0,1.0,0 days 00:14:29.105000,NaT,NaT,0 days 00:00:33.099000,...,True,McLaren,0 days 00:14:29.105000,NaT,1,NaN,False,,False,False
1,0 days 00:17:49.307000,NOR,1,0 days 00:01:20.897000,2.0,1.0,NaT,NaT,0 days 00:00:28.261000,0 days 00:00:28.981000,...,True,McLaren,0 days 00:16:28.410000,NaT,1,NaN,False,,False,True
2,0 days 00:20:10.701000,NOR,1,0 days 00:02:21.394000,3.0,1.0,NaT,NaT,0 days 00:00:51.920000,0 days 00:00:57.092000,...,True,McLaren,0 days 00:17:49.307000,NaT,1,NaN,False,,False,True
3,0 days 00:21:47.637000,NOR,1,0 days 00:01:36.936000,4.0,1.0,NaT,NaT,0 days 00:00:31.519000,0 days 00:00:34.621000,...,True,McLaren,0 days 00:20:10.701000,NaT,1,NaN,False,,False,True
4,0 days 00:23:09.982000,NOR,1,0 days 00:01:22.345000,5.0,1.0,NaT,NaT,0 days 00:00:28.092000,0 days 00:00:28.814000,...,True,McLaren,0 days 00:21:47.637000,NaT,1,NaN,False,,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
567,0 days 01:12:49.107000,BEA,87,0 days 00:01:26.681000,24.0,5.0,NaT,NaT,0 days 00:00:29.928000,0 days 00:00:31.925000,...,False,Haas F1 Team,0 days 01:11:22.426000,NaT,1,NaN,False,,False,True
568,0 days 01:14:16.657000,BEA,87,0 days 00:01:27.550000,25.0,5.0,NaT,NaT,0 days 00:00:30.321000,0 days 00:00:32.290000,...,False,Haas F1 Team,0 days 01:12:49.107000,NaT,1,NaN,False,,False,True
569,0 days 01:16:54.912000,BEA,87,NaT,26.0,5.0,NaT,NaT,0 days 00:00:37.366000,0 days 00:00:37.227000,...,False,Haas F1 Team,0 days 01:14:16.657000,NaT,1,NaN,False,,False,False
570,0 days 01:19:08.496000,BEA,87,0 days 00:02:13.584000,27.0,5.0,NaT,NaT,0 days 00:00:31.474000,0 days 00:00:33.499000,...,False,Haas F1 Team,0 days 01:16:54.912000,NaT,1,NaN,False,,False,True
571,0 days 01:20:41.833000,BEA,87,0 days 00:01:33.337000,28.0,5.0,NaT,0 days 01:20:39.974000,0 days 00:00:32.871000,0 days 00:00:32.655000,...,False,Haas F1 Team,0 days 01:19:08.496000,NaT,1,NaN,False,,False,False

In [11]:
laps2 = session2.laps.copy()
laps2[laps2['Driver'] == 'ANT']

compound_adjustments = {
    'SOFT': 0.8, 
    'MEDIUM': 0.0, 
    'HARD': -0.7 
}

driver_paces = {}

# Assumes track gets about 1.5 seconds faster in 60 minutes (3600 seconds)
trackEvolutionPerSecond = 1.5 / 3600

for driver in session2.drivers:
    driverInfo = session2.get_driver(driver)
    abbr = driverInfo['Abbreviation']
    
    laps = session2.laps.pick_drivers(driver)
    actual_laps = laps.pick_accurate().pick_wo_box()

    # filter for long runs (5+ laps)
    long_runs = actual_laps.groupby('Stint').filter(lambda x: len(x) >= 5)
    pd.set_option('display.max_columns', None)

    # find the median time of the long run laps
    stint_median = long_runs['LapTime'].median()

    # create a cutoff threshold (anything 4 seconds slower than the median is discarded)
    # ensures no slow laps are included
    cutoff_threshold = stint_median + pd.to_timedelta(4, unit='s')
    clean_laps = long_runs[long_runs['LapTime'] <= cutoff_threshold]

    if not clean_laps.empty:
        # Track evolution
        
        driver_paces[driver] = clean_laps['LapTime'].median().total_seconds()

In [14]:
driver_paces = dict(sorted(driver_paces.items(), key=lambda item: item[1]))
driver_paces

{'43': 83.042,
 '12': 84.025,
 '3': 84.141,
 '16': 84.2605,
 '44': 84.611,
 '1': 84.6185,
 '6': 85.0785,
 '63': 85.096,
 '27': 85.298,
 '81': 85.4415,
 '30': 85.593,
 '41': 85.849,
 '5': 86.005,
 '10': 86.275,
 '87': 86.331,
 '31': 86.4895,
 '14': 86.5925,
 '23': 87.066,
 '55': 87.2285,
 '77': 87.564,
 '11': 87.729}

In [14]:
laps2 = session2.laps.copy()
laps2[laps2['Driver'] == 'ANT']

# Since soft is faster, add time to normalize to medium
# Hard is slower so subtract time to normalize to medium
compound_adjustments = {
    'SOFT': 0.5, 
    'MEDIUM': 0.0, 
    'HARD': -0.6
}

# Assumes track gets about 1.5 seconds faster in 60 minutes (3600 seconds)
trackEvolutionPerSecond = 1.5 / 3600

driverLongRuns = []

for driver in session2.drivers:
    driverInfo = session2.get_driver(driver)
    abbr = driverInfo['Abbreviation']
    
    laps = session2.laps.pick_drivers(driver)
    actual_laps = laps.pick_accurate().pick_wo_box()

    # group by both stint and compound
    grouped_stints = actual_laps.groupby(['Stint', 'Compound'])

    for (stint, compound), group in grouped_stints:
        stint_median = group['LapTime'].mean()

        # create a cutoff threshold (anything 4 seconds slower than the median is discarded)
        # ensures no slow laps are included
        cutoff_threshold = stint_median + pd.to_timedelta(4, unit='s')
        clean_laps = group[group['LapTime'] <= cutoff_threshold]
        
        # long runs must be at least 8 laps long
        if len(clean_laps) >= 8:
            avg_time = clean_laps['LapTime'].mean().total_seconds()

            evo_advantage = avg_time * trackEvolutionPerSecond

            rawPace = clean_laps['LapTime'].median().total_seconds()

            evo_corrected_pace = rawPace + evo_advantage

            # Compound adjustment
            # If its an unknown compound (wet tires) the default is 0
            adjValue = compound_adjustments.get(compound, 0.0)
            adjustedPace = evo_corrected_pace + adjValue

            driverLongRuns.append({
                'Driver': abbr,
                'Compound': compound,
                'Raw Pace': rawPace,
                'Adjusted Pace': adjustedPace
            })

df_pace = pd.DataFrame(driverLongRuns)
df_pace = df_pace.sort_values(by='Adjusted Pace')
df_pace

   Driver Compound  Raw Pace  Adjusted Pace
2     ANT     SOFT   84.0655      84.600805
0     NOR   MEDIUM   84.8140      84.849351
9     RUS   MEDIUM   85.0960      85.131508
5     LAW     HARD   85.7700      85.205937
7     LIN     HARD   85.9350      85.370930
11    PIA   MEDIUM   85.4415      85.477125
3     LEC     SOFT   84.9440      85.479495
12    BEA   MEDIUM   86.4535      86.489564
6     OCO   MEDIUM   86.4895      86.525596
4     ALB     HARD   87.3710      86.807531
8     SAI     HARD   87.4355      86.871883
1     PER   MEDIUM   87.7765      87.813173
10    BOT   MEDIUM   87.9060      87.942740

In [50]:
if not df_pace.empty:
    # If driver did multiple long runs, take their best adjusted pace
    bestPaces = df_pace.loc[df_pace.groupby('Driver')['Adjusted Pace'].idxmin()]

    # Sort by fastest adjusted pace
    bestPaces = bestPaces.sort_values(by='Adjusted Pace').reset_index(drop=True)

bestPaces

   Driver Compound   Raw Pace  Adjusted Pace
0     NOR   MEDIUM  84.842727      84.842727
1     RUS   MEDIUM  85.220076      85.220076
2     PIA   MEDIUM  85.499500      85.499500
3     LIN     HARD  86.231800      85.531800
4     ANT     SOFT  84.731875      85.531875
5     LAW     HARD  86.248777      85.548777
6     LEC     SOFT  85.188444      85.988444
7     BEA   MEDIUM  86.554000      86.554000
8     SAI     HARD  87.319333      86.619333
9     OCO   MEDIUM  86.630700      86.630700
10    ALB     HARD  87.673666      86.973666
11    PER   MEDIUM  88.014200      88.014200
12    BOT   MEDIUM  88.176625      88.176625

In [37]:
laps = session2.laps.pick_drivers('27')
actual_laps = laps.pick_accurate().pick_wo_box()

# group by both stint and compound
grouped_stints = actual_laps.groupby(['Stint', 'Compound'])
grouped_stints.groups
group = grouped_stints.get_group((1.0, 'HARD'))
group
stint_median = group['LapTime'].median()
stint_median
cutoff_threshold = stint_median + pd.to_timedelta(4, unit='s')
clean_laps = group[group['LapTime'] <= cutoff_threshold]
clean_laps

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,IsPersonalBest,Compound,TyreLife,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
274,0 days 00:16:46.755000,HUL,27,0 days 00:01:21.788000,2.0,1.0,NaT,NaT,0 days 00:00:28.367000,0 days 00:00:29.576000,0 days 00:00:23.845000,0 days 00:15:53.334000,0 days 00:16:22.910000,0 days 00:16:46.755000,300.0,244.0,258.0,323.0,True,HARD,2.0,True,Audi,0 days 00:15:24.967000,NaT,1,NaN,False,,False,True
276,0 days 00:20:41.853000,HUL,27,0 days 00:01:47.427000,4.0,1.0,NaT,NaT,0 days 00:00:28.597000,0 days 00:00:45.398000,0 days 00:00:33.432000,0 days 00:19:23.023000,0 days 00:20:08.421000,0 days 00:20:41.853000,297.0,144.0,265.0,318.0,False,HARD,4.0,True,Audi,0 days 00:18:54.426000,NaT,1,NaN,False,,False,True
277,0 days 00:22:03.026000,HUL,27,0 days 00:01:21.173000,5.0,1.0,NaT,NaT,0 days 00:00:28.349000,0 days 00:00:29.448000,0 days 00:00:23.376000,0 days 00:21:10.202000,0 days 00:21:39.650000,0 days 00:22:03.026000,294.0,249.0,254.0,320.0,True,HARD,5.0,True,Audi,0 days 00:20:41.853000,NaT,1,NaN,False,,False,True
279,0 days 00:25:44.038000,HUL,27,0 days 00:01:46.294000,7.0,1.0,NaT,NaT,0 days 00:00:39.133000,0 days 00:00:40.376000,0 days 00:00:26.785000,0 days 00:24:36.877000,0 days 00:25:17.253000,0 days 00:25:44.038000,176.0,220.0,265.0,250.0,False,HARD,7.0,True,Audi,0 days 00:23:57.744000,NaT,1,NaN,False,,False,True
280,0 days 00:27:05.105000,HUL,27,0 days 00:01:21.067000,8.0,1.0,NaT,NaT,0 days 00:00:28.251000,0 days 00:00:29.228000,0 days 00:00:23.588000,0 days 00:26:12.289000,0 days 00:26:41.517000,0 days 00:27:05.105000,293.0,247.0,254.0,320.0,True,HARD,8.0,True,Audi,0 days 00:25:44.038000,NaT,1,NaN,False,,False,True

In [57]:
import numpy as np
import pandas as pd

driverLongRuns = []

for driver in session2.drivers:

    driverInfo = session2.get_driver(driver)
    abbr = driverInfo['Abbreviation']

    laps = session2.laps.pick_drivers(driver)

    actual_laps = (
        laps
        .pick_accurate()
        .pick_wo_box()
        .copy()
    )

    # Need lap time in seconds
    actual_laps['LapTimeSeconds'] = (
        actual_laps['LapTime']
        .dt.total_seconds()
    )

    grouped_stints = actual_laps.groupby(
        ['Stint', 'Compound']
    )

    for (stint, compound), group in grouped_stints:

        group = group.dropna(
            subset=['LapTimeSeconds', 'TyreLife']
        ).copy()

        # Need at least 8 laps
        if len(group) < 8:
            continue

        # Remove obvious slow laps
        median = group['LapTimeSeconds'].median()

        clean_laps = group[
            group['LapTimeSeconds'] <= median + 4
        ].copy()

        if len(clean_laps) < 8:
            continue

        # Fit:
        # LapTime = BasePace + Degradation * TyreLife
        x = clean_laps['TyreLife'].values
        y = clean_laps['LapTimeSeconds'].values

        degradation, base_pace = np.polyfit(x, y, 1)

        reference_tyre_life = 5

        reference_pace = (
            base_pace +
            degradation * reference_tyre_life
        )
        
        driverLongRuns.append({
            'Driver': abbr,
            'Stint': stint,
            'Compound': compound,
            'Reference Pace': reference_pace,
            'Pace Slope': degradation,
            'Laps': len(clean_laps)
        })

df_pace = pd.DataFrame(driverLongRuns)
df_pace

   Driver  Stint Compound  Reference Pace  Pace Slope  Laps
0     NOR    3.0   MEDIUM       83.360400    0.185291    11
1     PER    4.0   MEDIUM       86.111755    0.157490     9
2     LEC    4.0     SOFT       83.552544    0.233700     9
3     ALB    3.0     HARD       86.371404    0.089811    12
4     LAW    5.0     HARD       84.274589    0.137497     8
5     OCO    4.0   MEDIUM       85.436182    0.113764    10
6     LIN    4.0     HARD       87.069127   -0.079745    10
7     SAI    3.0     HARD       86.495994    0.065867    12
8     RUS    4.0   MEDIUM       83.080275    0.194527    13
9     BOT    4.0   MEDIUM       84.347929    0.283607     8
10    PIA    5.0   MEDIUM       84.483500    0.096762     8
11    BEA    5.0   MEDIUM       85.143333    0.122667     8

In [7]:
import numpy as np
import pandas as pd

driverLongRuns = []

REFERENCE_TYRE_LIFE = 5

for driver in session2.drivers:

    driverInfo = session2.get_driver(driver)
    abbr = driverInfo["Abbreviation"]

    laps = session2.laps.pick_drivers(driver)

    actual_laps = (
        laps
        .pick_accurate()
        .pick_wo_box()
        .copy()
    )

    actual_laps["LapTimeSeconds"] = (
        actual_laps["LapTime"].dt.total_seconds()
    )

    actual_laps = actual_laps.dropna(
        subset=[
            "LapTimeSeconds",
            "TyreLife",
            "Compound",
            "Stint"
        ]
    )

    grouped_stints = actual_laps.groupby(
        ["Stint", "Compound"]
    )

    for (stint, compound), group in grouped_stints:

        group = group.sort_values("LapNumber").copy()

        # ---------------------------------------------------------
        # Minimum stint length
        # ---------------------------------------------------------

        if len(group) < 8:
            continue

        # ---------------------------------------------------------
        # Remove obviously slow laps
        # ---------------------------------------------------------

        median = group["LapTimeSeconds"].median()

        # Anything > 3 seconds slower than median is suspicious
        group = group[
            group["LapTimeSeconds"] <= median + 3
        ].copy()

        if len(group) < 5:
            continue

        # ---------------------------------------------------------
        # Remove statistical outliers using IQR
        # ---------------------------------------------------------

        q1 = group["LapTimeSeconds"].quantile(0.25)
        q3 = group["LapTimeSeconds"].quantile(0.75)

        iqr = q3 - q1

        lower_bound = q1 - 1.5 * iqr
        upper_bound = q3 + 1.5 * iqr

        group = group[
            group["LapTimeSeconds"].between(
                lower_bound,
                upper_bound
            )
        ].copy()

        if len(group) < 8:
            continue

        # ---------------------------------------------------------
        # Fit pace trend
        # ---------------------------------------------------------

        x = group["TyreLife"].values
        y = group["LapTimeSeconds"].values

        slope, intercept = np.polyfit(x, y, 1)

        predictions = intercept + slope * x

        ss_res = np.sum(
            (y - predictions) ** 2
        )

        ss_tot = np.sum(
            (y - np.mean(y)) ** 2
        )

        if ss_tot == 0:
            r_squared = 0
        else:
            r_squared = 1 - (ss_res / ss_tot)

        # ---------------------------------------------------------
        # Don't trust extremely weak regressions
        # ---------------------------------------------------------

        if r_squared < 0.15:
            continue

        # ---------------------------------------------------------
        # Don't extrapolate outside observed tire life
        #
        # If the stint starts at TyreLife 12, predicting pace at
        # TyreLife 5 is dangerous.
        # ---------------------------------------------------------

        min_tyre_life = group["TyreLife"].min()
        max_tyre_life = group["TyreLife"].max()

        reference_tyre_life = np.clip(
            REFERENCE_TYRE_LIFE,
            min_tyre_life,
            max_tyre_life
        )

        reference_pace = (
            intercept +
            slope * reference_tyre_life
        )

        # ---------------------------------------------------------
        # Additional sanity check
        # ---------------------------------------------------------

        # Reference pace should be reasonably close to the actual
        # laps in the stint.
        actual_median = group["LapTimeSeconds"].median()

        if abs(reference_pace - actual_median) > 2:
            continue

        # ---------------------------------------------------------
        # Store
        # ---------------------------------------------------------

        driverLongRuns.append({
            "Driver": abbr,
            "Stint": stint,
            "Compound": compound,
            "Reference Pace": reference_pace,
            "Pace Slope": slope,
            "Laps": len(group),
            "R2": r_squared,
            "Start TyreLife": min_tyre_life,
            "End TyreLife": max_tyre_life
        })


df_pace = pd.DataFrame(driverLongRuns)

# -------------------------------------------------------------
# Normalize against fastest observed stint
# -------------------------------------------------------------

if not df_pace.empty:

    fastest_pace = df_pace["Reference Pace"].min()

    df_pace["Race Pace %"] = (
        (df_pace["Reference Pace"] - fastest_pace)
        / fastest_pace
    ) * 100

    df_pace = df_pace.sort_values(
        "Race Pace %"
    ).reset_index(drop=True)

print(
    df_pace[
        [
            "Driver",
            "Stint",
            "Compound",
            "Reference Pace",
            "Race Pace %",
            "Pace Slope",
            "Laps",
            "R2",
            "Start TyreLife",
            "End TyreLife"
        ]
    ]
)
df_pace

  Driver  Stint Compound  Reference Pace  Race Pace %  Pace Slope  Laps  \
0    NOR    3.0   MEDIUM       83.916273     0.000000    0.185291    11
1    LEC    4.0     SOFT       84.253644     0.402034    0.233700     9
2    RUS    4.0   MEDIUM       84.306259     0.464732    0.115357    12
3    PIA    5.0   MEDIUM       85.160833     1.483098    0.096762     8
4    OCO    4.0   MEDIUM       85.577704     1.979868    0.139528     9
5    ALB    3.0     HARD       86.797677     3.433666    0.081386    10
6    SAI    3.0     HARD       86.957064     3.623602    0.065867    12
7    BOT    4.0   MEDIUM       87.184000     3.894033    0.283607     8

         R2  Start TyreLife  End TyreLife
0  0.740566             8.0          18.0
1  0.251945             8.0          16.0
2  0.222116            10.0          22.0
3  0.579046            12.0          19.0
4  0.902448            11.0          20.0
5  0.644084            14.0          25.0
6  0.335170            12.0          23.0
7  0.750515            15.0          22.0

,Driver,Stint,Compound,Reference Pace,Pace Slope,Laps,R2,Start TyreLife,End TyreLife,Race Pace %
0,NOR,3.0,MEDIUM,83.916273,0.185291,11,0.740566,8.0,18.0,0.000000
1,LEC,4.0,SOFT,84.253644,0.233700,9,0.251945,8.0,16.0,0.402034
2,RUS,4.0,MEDIUM,84.306259,0.115357,12,0.222116,10.0,22.0,0.464732
3,PIA,5.0,MEDIUM,85.160833,0.096762,8,0.579046,12.0,19.0,1.483098
4,OCO,4.0,MEDIUM,85.577704,0.139528,9,0.902448,11.0,20.0,1.979868
5,ALB,3.0,HARD,86.797677,0.081386,10,0.644084,14.0,25.0,3.433666
6,SAI,3.0,HARD,86.957064,0.065867,12,0.335170,12.0,23.0,3.623602
7,BOT,4.0,MEDIUM,87.184000,0.283607,8,0.750515,15.0,22.0,3.894033

In [60]:
# Fastest observed reference pace
fastest_pace = df_pace["Reference Pace"].min()

# Percentage slower than fastest
df_pace["Race Pace %"] = (
    (df_pace["Reference Pace"] - fastest_pace)
    / fastest_pace
) * 100

# Sort by Race Pace %
df_pace = df_pace.sort_values(
    "Race Pace %"
).reset_index(drop=True)

print(
    df_pace[
        [
            "Driver",
            "Compound",
            "Reference Pace",
            "Race Pace %",
            "Pace Slope",
            "Laps",
            "R2"
        ]
    ]
)

   Driver Compound  Reference Pace  Race Pace %  Pace Slope  Laps        R2
0     NOR   MEDIUM       83.360400     0.000000    0.185291    11  0.740566
1     LEC     SOFT       83.552544     0.230498    0.233700     9  0.251945
2     RUS   MEDIUM       83.729476     0.442747    0.115357    12  0.222116
3     LAW     HARD       84.274589     1.096670    0.137497     8  0.294074
4     PIA   MEDIUM       84.483500     1.347282    0.096762     8  0.579046
5     OCO   MEDIUM       84.740534     1.655623    0.139528     9  0.902448
6     LIN     HARD       84.817107     1.747481    0.100393     8  0.562571
7     ALB     HARD       86.065204     3.244710    0.081386    10  0.644084
8     SAI     HARD       86.495994     3.761491    0.065867    12  0.335170
9     LEC   MEDIUM       98.003139    17.565581   -0.080250     9  0.000173
10    BOT   MEDIUM      100.788836    20.907333    0.050218    11  0.000135
11    ALB     HARD      101.577364    21.853258   -1.157376    10  0.057553

In [4]:
qpace = {
 '44': 0.2883537047353921,
 '16': 0.35626267907114617,
 '1': 0.6514795281948139,
 '63': 0.7209262901911908,
 '12': 0.7331241713221844,
 '3': 0.7694065419422823,
 '81': 0.9282909470851828,
 '6': 1.0993955659389323,
 '30': 1.740596673711035,
 '27': 1.8692560300119592,
 '5': 2.086800833148885,
 '41': 2.1131587150744084,
 '10': 2.3121521681017043,
 '31': 2.7313878301418217,
 '87': 2.7979227169177534,
 '43': 3.029001925831425,
 '23': 3.2417849009962696,
 '55': 3.5535988844515267,
 '14': 3.7740488904012466,
 '11': 3.959510982833512,
 '77': 4.090090298661223,
 '18': 4.766860833976087
}
qpace

{'44': 0.2883537047353921,
 '16': 0.35626267907114617,
 '1': 0.6514795281948139,
 '63': 0.7209262901911908,
 '12': 0.7331241713221844,
 '3': 0.7694065419422823,
 '81': 0.9282909470851828,
 '6': 1.0993955659389323,
 '30': 1.740596673711035,
 '27': 1.8692560300119592,
 '5': 2.086800833148885,
 '41': 2.1131587150744084,
 '10': 2.3121521681017043,
 '31': 2.7313878301418217,
 '87': 2.7979227169177534,
 '43': 3.029001925831425,
 '23': 3.2417849009962696,
 '55': 3.5535988844515267,
 '14': 3.7740488904012466,
 '11': 3.959510982833512,
 '77': 4.090090298661223,
 '18': 4.766860833976087}

In [5]:
import fastf1
import pandas as pd
fastf1.Cache.enable_cache('D:\\Programming\\Python\\AI\\F1 Fantasy\\cache')

In [6]:
events = fastf1.get_events_remaining()
nextRound = events.iloc[0].RoundNumber-1

In [7]:
nextRound

np.int64(11)

In [9]:
rpace = {}

session = fastf1.get_session(2026, nextRound-1, 'R')
session.load(telemetry=False)
for driver in session.drivers:
    rpace[driver] = []

for round in range(1, nextRound):
    session = fastf1.get_session(2026, round, 'R')
    session.load(telemetry=False)

    results = session.results[['FullName', 'Position', 'Status']]

    for index, driver in results.iterrows():
        if not driver.Status == 'Retired':
            rpace[index].append(driver.Position)

core           INFO 	Loading data for Belgian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '12'
core        WARNING 	Driver 12 completed the race distance 00:00.045000 before the recorded end of the session.
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['12', '16', '3', '44', '81', '6', '1', '5', '41', '43', '10', '30', '27', '87', '23', '55', '31', '77', '14', '18', '11', '63']
core           INFO 	Loading data for Australian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 81)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 27)
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['63', '12', '16', '44', '1', '3', '87', '41', '5', '10', '31', '23', '30', '43', '55', '11', '18', '14', '77', '6', '81', '27']
core           INFO 	Loading data for Chinese Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 81)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 1)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 5)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 23)
core        WARNING 	Driver 12 completed the race distance 00:00.022000 before the recorded end of the session.
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['12', '63', '44', '16', '87', '10', '30', '6', '55', '43', '27', '41', '77', '31', '11', '3', '14', '18', '81', '1', '5', '23']
core           INFO 	Loading data for Japanese Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['12', '81', '16', '63', '1', '44', '10', '3', '30', '31', '27', '6', '5', '41', '55', '43', '11', '14', '77', '23', '18', '87']
core           INFO 	Loading data for Miami Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 12 completed the race distance 00:00.027000 before the recorded end of the session.
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['12', '1', '81', '63', '3', '44', '43', '16', '55', '23', '87', '5', '31', '41', '14', '11', '18', '77', '27', '30', '10', '6']
core           INFO 	Loading data for Canadian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 41)
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['12', '44', '3', '16', '6', '43', '30', '10', '55', '87', '81', '27', '5', '31', '18', '77', '11', '1', '63', '14', '23', '41']
core           INFO 	Loading data for Monaco Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['12', '44', '10', '6', '81', '30', '41', '23', '31', '14', '5', '63', '27', '43', '11', '55', '16', '18', '1', '87', '77', '3']
core           INFO 	Loading data for Barcelona Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '87'
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['44', '63', '1', '3', '81', '6', '10', '30', '41', '43', '5', '55', '31', '11', '16', '12', '87', '23', '14', '27', '77', '18']
core           INFO 	Loading data for Austrian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 63 completed the race distance 00:00.530000 before the recorded end of the session.
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['63', '3', '12', '81', '44', '6', '1', '16', '30', '41', '5', '27', '10', '87', '43', '31', '23', '14', '18', '55', '11', '77']
core           INFO 	Loading data for British Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['16', '63', '44', '1', '6', '30', '41', '5', '43', '10', '81', '87', '31', '11', '12', '77', '55', '14', '18', '3', '23', '27']
core           INFO 	Loading data for Belgian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '12'
core        WARNING 	Driver 12 completed the race distance 00:00.045000 before the recorded end of the session.
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['12', '16', '3', '44', '81', '6', '1', '5', '41', '43', '10', '30', '27', '87', '23', '55', '31', '77', '14', '18', '11', '63']

In [10]:
rpace

{'12': [2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 3.0, 15.0, 1.0],
 '16': [3.0, 4.0, 3.0, 8.0, 4.0, 8.0, 1.0, 2.0],
 '3': [6.0, 8.0, 5.0, 3.0, 4.0, 2.0, 3.0],
 '44': [4.0, 3.0, 6.0, 6.0, 2.0, 2.0, 1.0, 5.0, 3.0, 4.0],
 '81': [21.0, 19.0, 2.0, 3.0, 11.0, 5.0, 5.0, 4.0, 11.0, 5.0],
 '6': [8.0, 12.0, 5.0, 4.0, 6.0, 6.0, 5.0, 6.0],
 '1': [5.0, 20.0, 5.0, 2.0, 3.0, 7.0, 4.0, 7.0],
 '5': [9.0, 21.0, 13.0, 12.0, 13.0, 11.0, 11.0, 11.0, 8.0, 8.0],
 '41': [8.0, 12.0, 14.0, 14.0, 22.0, 7.0, 9.0, 10.0, 7.0, 9.0],
 '43': [14.0, 10.0, 16.0, 7.0, 6.0, 14.0, 10.0, 15.0, 9.0, 10.0],
 '10': [10.0, 6.0, 7.0, 8.0, 3.0, 7.0, 13.0, 10.0, 11.0],
 '30': [13.0, 7.0, 9.0, 7.0, 6.0, 8.0, 9.0, 6.0, 12.0],
 '27': [22.0, 11.0, 11.0, 12.0, 13.0, 12.0, 13.0],
 '87': [7.0, 5.0, 11.0, 10.0, 14.0, 12.0, 14.0],
 '23': [12.0, 22.0, 20.0, 10.0, 8.0, 18.0, 17.0, 15.0],
 '55': [15.0, 9.0, 15.0, 9.0, 9.0, 12.0, 17.0, 16.0],
 '31': [11.0, 14.0, 10.0, 13.0, 14.0, 9.0, 13.0, 16.0, 13.0, 17.0],
 '77': [13.0, 19.0, 18.0, 16.0, 16.0, 18.0],
 '14': [18.0, 15.0, 10.0, 18.0, 18.0, 19.0],
 '18': [17.0, 17.0, 15.0, 19.0],
 '11': [16.0, 15.0, 17.0, 16.0, 15.0, 14.0, 14.0],
 '63': [1.0, 2.0, 4.0, 4.0, 12.0, 2.0, 1.0, 2.0]}

In [7]:
session = fastf1.get_session(2026, nextRound-1, 'R')
session.load(telemetry=False)
session.results

core           INFO 	Loading data for Belgian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '12'
core        WARNING 	Driver 12 completed the race distance 00:00.045000 before the recorded end of the session.
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['12', '16', '3', '44', '81', '6', '1', '5', '41', '43', '10', '30', '27', '87', '23', '55', '31', '77', '14', '18', '11', '63']

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
12,12,K ANTONELLI,ANT,antonelli,Mercedes,00D7B6,mercedes,Kimi,Antonelli,Kimi Antonelli,...,1.0,1,1.0,NaT,NaT,NaT,0 days 01:24:42.479000,Finished,25.0,44.0
16,16,C LECLERC,LEC,leclerc,Ferrari,ED1131,ferrari,Charles,Leclerc,Charles Leclerc,...,2.0,2,4.0,NaT,NaT,NaT,0 days 00:00:01.952000,Finished,18.0,44.0
3,3,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,4781D7,red_bull,Max,Verstappen,Max Verstappen,...,3.0,3,2.0,NaT,NaT,NaT,0 days 00:00:11.586000,Finished,15.0,44.0
44,44,L HAMILTON,HAM,hamilton,Ferrari,ED1131,ferrari,Lewis,Hamilton,Lewis Hamilton,...,4.0,4,5.0,NaT,NaT,NaT,0 days 00:00:17.245000,Finished,12.0,44.0
81,81,O PIASTRI,PIA,piastri,McLaren,F47600,mclaren,Oscar,Piastri,Oscar Piastri,...,5.0,5,6.0,NaT,NaT,NaT,0 days 00:00:18.988000,Finished,10.0,44.0
6,6,I HADJAR,HAD,hadjar,Red Bull Racing,4781D7,red_bull,Isack,Hadjar,Isack Hadjar,...,6.0,6,21.0,NaT,NaT,NaT,0 days 00:00:23.307000,Finished,8.0,44.0
1,1,L NORRIS,NOR,norris,McLaren,F47600,mclaren,Lando,Norris,Lando Norris,...,7.0,7,13.0,NaT,NaT,NaT,0 days 00:00:24.014000,Finished,6.0,44.0
5,5,G BORTOLETO,BOR,bortoleto,Audi,F50537,audi,Gabriel,Bortoleto,Gabriel Bortoleto,...,8.0,8,8.0,NaT,NaT,NaT,0 days 00:00:49.140000,Finished,4.0,44.0
41,41,A LINDBLAD,LIN,arvid_lindblad,Racing Bulls,6C98FF,rb,Arvid,Lindblad,Arvid Lindblad,...,9.0,9,7.0,NaT,NaT,NaT,0 days 00:00:50.406000,Finished,2.0,44.0
43,43,F COLAPINTO,COL,colapinto,Alpine,00A1E8,alpine,Franco,Colapinto,Franco Colapinto,...,10.0,10,11.0,NaT,NaT,NaT,0 days 00:01:16.037000,Finished,1.0,44.0
10,10,P GASLY,GAS,gasly,Alpine,00A1E8,alpine,Pierre,Gasly,Pierre Gasly,...,11.0,11,10.0,NaT,NaT,NaT,0 days 00:01:16.991000,Finished,0.0,44.0
30,30,L LAWSON,LAW,lawson,Racing Bulls,6C98FF,rb,Liam,Lawson,Liam Lawson,...,12.0,12,9.0,NaT,NaT,NaT,0 days 00:01:17.523000,Finished,0.0,44.0
27,27,N HULKENBERG,HUL,hulkenberg,Audi,F50537,audi,Nico,Hulkenberg,Nico Hulkenberg,...,13.0,13,12.0,NaT,NaT,NaT,0 days 00:01:18.348000,Finished,0.0,44.0
87,87,O BEARMAN,BEA,bearman,Haas F1 Team,9C9FA2,haas,Oliver,Bearman,Oliver Bearman,...,14.0,14,14.0,NaT,NaT,NaT,0 days 00:01:34.465000,Finished,0.0,44.0
23,23,A ALBON,ALB,albon,Williams,1868DB,williams,Alexander,Albon,Alexander Albon,...,15.0,15,15.0,NaT,NaT,NaT,0 days 00:01:44.684000,Finished,0.0,44.0
55,55,C SAINZ,SAI,sainz,Williams,1868DB,williams,Carlos,Sainz,Carlos Sainz,...,16.0,16,19.0,NaT,NaT,NaT,0 days 00:01:45.856000,Finished,0.0,44.0
31,31,E OCON,OCO,ocon,Haas F1 Team,9C9FA2,haas,Esteban,Ocon,Esteban Ocon,...,17.0,17,16.0,NaT,NaT,NaT,0 days 00:01:50.925000,Finished,0.0,44.0
77,77,V BOTTAS,BOT,bottas,Cadillac,909090,cadillac,Valtteri,Bottas,Valtteri Bottas,...,18.0,18,17.0,NaT,NaT,NaT,0 days 00:01:00.979000,Lapped,0.0,43.0
14,14,F ALONSO,ALO,alonso,Aston Martin,229971,aston_martin,Fernando,Alonso,Fernando Alonso,...,19.0,19,22.0,NaT,NaT,NaT,0 days 00:00:20.848000,Lapped,0.0,42.0
18,18,L STROLL,STR,stroll,Aston Martin,229971,aston_martin,Lance,Stroll,Lance Stroll,...,20.0,R,20.0,NaT,NaT,NaT,NaT,Retired,0.0,25.0
11,11,S PEREZ,PER,perez,Cadillac,909090,cadillac,Sergio,Perez,Sergio Perez,...,21.0,R,18.0,NaT,NaT,NaT,NaT,Retired,0.0,13.0
63,63,G RUSSELL,RUS,russell,Mercedes,00D7B6,mercedes,George,Russell,George Russell,...,22.0,R,3.0,NaT,NaT,NaT,NaT,Retired,0.0,0.0

In [11]:
decay = 0.85
predictedRPace = {}

for driverNumber in qpace:
    decaySum = 0
    decayWeights = 0
    
    for i in range(len(rpace[driverNumber])):
        # get opposite index to iterate backwards (to go by most recent values)
        j = len(rpace[driverNumber]) - i - 1
        if not pd.isna(rpace[driverNumber][j]):
            if i != 0:
                decaySum += (rpace[driverNumber][j]) * (decay ** i) 
                decayWeights += decay ** i
            else:
                decaySum += rpace[driverNumber][j]
                decayWeights += 1

    predictedRPace[driverNumber] = decaySum/decayWeights
    #print(f"{driverNumber}: {decaySum/decayWeights}")

predictedRPace = dict(sorted(predictedRPace.items(), key=lambda item: item[1]))
predictedRPace

{'63': 3.423094050511717,
 '44': 3.4810894851484857,
 '12': 3.6583402235061664,
 '16': 3.9306694801192856,
 '3': 3.9419363556452596,
 '6': 6.116768264325954,
 '1': 6.125340804255792,
 '81': 7.398959790238133,
 '30': 8.5766278731196,
 '10': 8.900921959216891,
 '41': 10.460757368424723,
 '5': 10.741768722265668,
 '43': 10.895411417066684,
 '87': 11.272115873907316,
 '27': 12.999734520792371,
 '55': 13.237716850173891,
 '31': 13.62954767567119,
 '11': 15.040906851777256,
 '23': 15.176376188862113,
 '14': 16.680497433786716,
 '77': 16.834025074888178,
 '18': 17.094143490369905}

In [5]:
session = fastf1.get_session(2026, nextRound-1, 'R')
session.load(telemetry=False)
session.results

core           INFO 	Loading data for Belgian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '12'
core        WARNING 	Driver 12 completed the race distance 00:00.045000 before the recorded end of the session.
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['12', '16', '3', '44', '81', '6', '1', '5', '41', '43', '10', '30', '27', '87', '23', '55', '31', '77', '14', '18', '11', '63']

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
12,12,K ANTONELLI,ANT,antonelli,Mercedes,00D7B6,mercedes,Kimi,Antonelli,Kimi Antonelli,...,1.0,1,1.0,NaT,NaT,NaT,0 days 01:24:42.479000,Finished,25.0,44.0
16,16,C LECLERC,LEC,leclerc,Ferrari,ED1131,ferrari,Charles,Leclerc,Charles Leclerc,...,2.0,2,4.0,NaT,NaT,NaT,0 days 00:00:01.952000,Finished,18.0,44.0
3,3,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,4781D7,red_bull,Max,Verstappen,Max Verstappen,...,3.0,3,2.0,NaT,NaT,NaT,0 days 00:00:11.586000,Finished,15.0,44.0
44,44,L HAMILTON,HAM,hamilton,Ferrari,ED1131,ferrari,Lewis,Hamilton,Lewis Hamilton,...,4.0,4,5.0,NaT,NaT,NaT,0 days 00:00:17.245000,Finished,12.0,44.0
81,81,O PIASTRI,PIA,piastri,McLaren,F47600,mclaren,Oscar,Piastri,Oscar Piastri,...,5.0,5,6.0,NaT,NaT,NaT,0 days 00:00:18.988000,Finished,10.0,44.0
6,6,I HADJAR,HAD,hadjar,Red Bull Racing,4781D7,red_bull,Isack,Hadjar,Isack Hadjar,...,6.0,6,21.0,NaT,NaT,NaT,0 days 00:00:23.307000,Finished,8.0,44.0
1,1,L NORRIS,NOR,norris,McLaren,F47600,mclaren,Lando,Norris,Lando Norris,...,7.0,7,13.0,NaT,NaT,NaT,0 days 00:00:24.014000,Finished,6.0,44.0
5,5,G BORTOLETO,BOR,bortoleto,Audi,F50537,audi,Gabriel,Bortoleto,Gabriel Bortoleto,...,8.0,8,8.0,NaT,NaT,NaT,0 days 00:00:49.140000,Finished,4.0,44.0
41,41,A LINDBLAD,LIN,arvid_lindblad,Racing Bulls,6C98FF,rb,Arvid,Lindblad,Arvid Lindblad,...,9.0,9,7.0,NaT,NaT,NaT,0 days 00:00:50.406000,Finished,2.0,44.0
43,43,F COLAPINTO,COL,colapinto,Alpine,00A1E8,alpine,Franco,Colapinto,Franco Colapinto,...,10.0,10,11.0,NaT,NaT,NaT,0 days 00:01:16.037000,Finished,1.0,44.0
10,10,P GASLY,GAS,gasly,Alpine,00A1E8,alpine,Pierre,Gasly,Pierre Gasly,...,11.0,11,10.0,NaT,NaT,NaT,0 days 00:01:16.991000,Finished,0.0,44.0
30,30,L LAWSON,LAW,lawson,Racing Bulls,6C98FF,rb,Liam,Lawson,Liam Lawson,...,12.0,12,9.0,NaT,NaT,NaT,0 days 00:01:17.523000,Finished,0.0,44.0
27,27,N HULKENBERG,HUL,hulkenberg,Audi,F50537,audi,Nico,Hulkenberg,Nico Hulkenberg,...,13.0,13,12.0,NaT,NaT,NaT,0 days 00:01:18.348000,Finished,0.0,44.0
87,87,O BEARMAN,BEA,bearman,Haas F1 Team,9C9FA2,haas,Oliver,Bearman,Oliver Bearman,...,14.0,14,14.0,NaT,NaT,NaT,0 days 00:01:34.465000,Finished,0.0,44.0
23,23,A ALBON,ALB,albon,Williams,1868DB,williams,Alexander,Albon,Alexander Albon,...,15.0,15,15.0,NaT,NaT,NaT,0 days 00:01:44.684000,Finished,0.0,44.0
55,55,C SAINZ,SAI,sainz,Williams,1868DB,williams,Carlos,Sainz,Carlos Sainz,...,16.0,16,19.0,NaT,NaT,NaT,0 days 00:01:45.856000,Finished,0.0,44.0
31,31,E OCON,OCO,ocon,Haas F1 Team,9C9FA2,haas,Esteban,Ocon,Esteban Ocon,...,17.0,17,16.0,NaT,NaT,NaT,0 days 00:01:50.925000,Finished,0.0,44.0
77,77,V BOTTAS,BOT,bottas,Cadillac,909090,cadillac,Valtteri,Bottas,Valtteri Bottas,...,18.0,18,17.0,NaT,NaT,NaT,0 days 00:01:00.979000,Lapped,0.0,43.0
14,14,F ALONSO,ALO,alonso,Aston Martin,229971,aston_martin,Fernando,Alonso,Fernando Alonso,...,19.0,19,22.0,NaT,NaT,NaT,0 days 00:00:20.848000,Lapped,0.0,42.0
18,18,L STROLL,STR,stroll,Aston Martin,229971,aston_martin,Lance,Stroll,Lance Stroll,...,20.0,R,20.0,NaT,NaT,NaT,NaT,Retired,0.0,25.0
11,11,S PEREZ,PER,perez,Cadillac,909090,cadillac,Sergio,Perez,Sergio Perez,...,21.0,R,18.0,NaT,NaT,NaT,NaT,Retired,0.0,13.0
63,63,G RUSSELL,RUS,russell,Mercedes,00D7B6,mercedes,George,Russell,George Russell,...,22.0,R,3.0,NaT,NaT,NaT,NaT,Retired,0.0,0.0

In [7]:
session.results.columns

Index(['DriverNumber', 'BroadcastName', 'Abbreviation', 'DriverId', 'TeamName',
       'TeamColor', 'TeamId', 'FirstName', 'LastName', 'FullName',
       'HeadshotUrl', 'CountryCode', 'Position', 'ClassifiedPosition',
       'GridPosition', 'Q1', 'Q2', 'Q3', 'Time', 'Status', 'Points', 'Laps'],
      dtype='object')

In [8]:
training_rows = []

# Loop across multiple seasons (e.g., 2023 to 2025)
for year in [2023, 2024, 2025]:
    # Retrieve the official schedule for that year
    schedule = fastf1.get_event_schedule(year)
    
    # Exclude pre-season testing events
    race_events = schedule[schedule['EventFormat'] != 'testing']
    
    for _, event in race_events.iterrows():
        try:
            # Safely request and load the race session
            race_session = fastf1.get_session(year, event['EventName'], 'R')
            race_session.load(laps=False, telemetry=False, weather=False) # Speed up load times
            
            results_df = race_session.results
            for _, driver_row in results_df.iterrows():
                training_rows.append({
                    'season': year,
                    'track': event['EventName'],
                    'driver': driver_row['BroadcastName'],
                    'team': driver_row['TeamName'],
                    'grid_position': driver_row['GridPosition'],
                    'target_finish_position': driver_row['ClassifiedPosition']
                })
        except Exception as e:
            # Handle instances of cancelled events or database drops gracefully
            continue

f1_ml_dataset = pd.DataFrame(training_rows)

core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '14', '55', '44', '18', '63', '77', '10', '23', '22', '2', '20', '21', '27', '24', '4', '31', '16', '81']
core           INFO 	Loading data for Saudi Arabian Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['11', '1', '14', '63', '44', '55', '16', '31', '10', '20', '22', '27', '24', '21', '81', '2', '4', '77', '23', '18']
core           INFO 	Loading data for Australian Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['1', '44', '14', '18', '11', '4', '27', '81', '24', '22', '77', '55', '10', '31', '21', '2', '20', '63', '23', '16']
core           INFO 	Loading data for Azerbaijan Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['11', '1', '16', '14', '55', '44', '18', '63', '4', '22', '81', '23', '20', '10', '31', '2', '27', '77', '24', '21']
core           INFO 	Loading data for Miami Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '14', '63', '55', '44', '16', '10', '31', '20', '22', '18', '77', '23', '27', '24', '4', '21', '81', '2']
core           INFO 	Loading data for Monaco Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['1', '14', '31', '44', '63', '16', '10', '55', '4', '81', '77', '21', '24', '23', '22', '11', '27', '2', '20', '18']
core           INFO 	Loading data for Spanish Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['1', '44', '63', '11', '55', '18', '14', '31', '24', '10', '16', '22', '81', '21', '27', '23', '4', '20', '77', '2']
core           INFO 	Loading data for Canadian Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['1', '14', '44', '16', '55', '11', '23', '31', '18', '77', '81', '10', '4', '22', '27', '24', '20', '21', '63', '2']
core           INFO 	Loading data for Austrian Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['1', '16', '11', '4', '14', '55', '63', '44', '18', '10', '23', '24', '2', '31', '77', '81', '21', '20', '22', '27']
core           INFO 	Loading data for British Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '44', '81', '63', '11', '14', '23', '16', '55', '2', '77', '27', '18', '24', '22', '21', '10', '20', '31']
core           INFO 	Loading data for Hungarian Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '11', '44', '81', '63', '16', '55', '14', '18', '23', '77', '3', '27', '22', '24', '20', '2', '31', '10']
core           INFO 	Loading data for Belgian Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '16', '44', '14', '63', '4', '31', '18', '22', '10', '77', '24', '23', '20', '3', '2', '27', '55', '81']
core           INFO 	Loading data for Dutch Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['1', '14', '10', '11', '55', '44', '4', '23', '81', '31', '18', '27', '40', '77', '22', '20', '63', '24', '16', '2']
core           INFO 	Loading data for Italian Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '55', '16', '63', '44', '23', '4', '14', '77', '40', '81', '2', '24', '10', '18', '27', '20', '31', '22']
core           INFO 	Loading data for Singapore Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['55', '4', '44', '16', '1', '10', '81', '11', '40', '20', '23', '24', '27', '2', '14', '63', '77', '31', '22', '18']
core           INFO 	Loading data for Japanese Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '81', '16', '44', '55', '63', '14', '31', '10', '40', '22', '24', '27', '20', '23', '2', '18', '11', '77']
events      WARNING 	Correcting user input 'Qatar Grand Prix' to 'Qatar Grand Prix'
core           INFO 	Loading data for Qatar Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['1', '81', '4', '63', '16', '14', '31', '77', '24', '11', '18', '10', '23', '20', '22', '27', '40', '2', '44', '55']
events      WARNING 	Correcting user input 'United States Grand Prix' to 'United States Grand Prix'
core           INFO 	Loading data for United States Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '55', '11', '63', '10', '18', '22', '23', '2', '27', '77', '24', '20', '3', '14', '81', '31', '44', '16']
core           INFO 	Loading data for Mexico City Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['1', '44', '16', '55', '4', '63', '3', '81', '23', '31', '10', '22', '27', '24', '77', '2', '18', '14', '20', '11']
core           INFO 	Loading data for São Paulo Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '14', '11', '18', '55', '10', '44', '22', '31', '2', '27', '3', '81', '63', '77', '24', '20', '23', '16']
core           INFO 	Loading data for Las Vegas Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['1', '16', '11', '31', '18', '55', '44', '63', '14', '81', '10', '23', '20', '3', '24', '2', '77', '22', '27', '4']
core           INFO 	Loading data for Abu Dhabi Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['1', '16', '63', '11', '4', '81', '14', '22', '44', '18', '3', '31', '10', '23', '27', '2', '24', '55', '77', '20']
core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '55', '16', '63', '4', '44', '81', '14', '18', '24', '20', '3', '22', '23', '27', '31', '10', '77', '2']
core           INFO 	Loading data for Saudi Arabian Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '16', '81', '14', '63', '38', '4', '44', '27', '23', '20', '31', '2', '22', '3', '77', '24', '18', '10']
core           INFO 	Loading data for Australian Grand Prix - Race [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!

In [10]:
f1_ml_dataset.head()

,season,track,driver,team,grid_position,target_finish_position
0,2023,Bahrain Grand Prix,M VERSTAPPEN,Red Bull Racing,1.0,1
1,2023,Bahrain Grand Prix,S PEREZ,Red Bull Racing,2.0,2
2,2023,Bahrain Grand Prix,F ALONSO,Aston Martin,5.0,3
3,2023,Bahrain Grand Prix,C SAINZ,Ferrari,4.0,4
4,2023,Bahrain Grand Prix,L HAMILTON,Mercedes,7.0,5

In [11]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_absolute_error, mean_squared_error
import xgboost as xgb

# --- STEP 1: SIMULATE HISTORICAL FASTF1 DATA ---
# (Replacing the f1_ml_dataset DataFrame compiled from the previous step)
np.random.seed(42)
num_samples = 1000

data = {
    'season': np.random.choice([2023, 2024, 2025], size=num_samples),
    'track': np.random.choice(['Silverstone', 'Monaco', 'Monza', 'Spa'], size=num_samples),
    'driver': np.random.choice(['M_VERSTAPPEN', 'L_HAMILTON', 'C_LECLERC', 'L_NORRIS'], size=num_samples),
    'team': np.random.choice(['Red Bull', 'Mercedes', 'Ferrari', 'McLaren'], size=num_samples),
    'grid_position': np.random.randint(1, 21, size=num_samples),
}

df = pd.DataFrame(data)

# Realistically, finishing position correlates heavily with starting grid position
# We add some random "race chaos" noise so the model has to learn patterns
df['target_finish_position'] = df['grid_position'] + np.random.randint(-3, 4, size=num_samples)
df['target_finish_position'] = df['target_finish_position'].clip(1, 20) # Keep positions within 1-20

# --- STEP 2: ENCODE CATEGORICAL VARIABLES ---
# Machine learning models require numbers, not strings.
encoders = {}
categorical_cols = ['track', 'driver', 'team']

for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    encoders[col] = le # Save encoders to decode predictions later

# --- STEP 3: SEPARATE FEATURES AND TARGET ---
X = df[['season', 'track', 'driver', 'team', 'grid_position']]
y = df['target_finish_position']

# Split data: 80% for training, 20% for testing the model's accuracy
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# --- STEP 4: INITIALIZE AND TRAIN THE MODEL ---
# XGBoost is highly effective for tabular data like race metrics
model = xgb.XGBRegressor(
    n_estimators=100,     # Number of decision trees
    max_depth=4,          # Depth of trees to prevent overfitting
    learning_rate=0.05,   # Step size shrinkage to maximize accuracy
    random_state=42
)

model.fit(X_train, y_train)

# --- STEP 5: EVALUATE PERFORMANCE ---
predictions = model.predict(X_test)

# Round predicted values to the nearest whole integer (since race positions are discrete)
final_predictions = np.round(predictions).astype(int)
final_predictions = np.clip(final_predictions, 1, 20)

mae = mean_absolute_error(y_test, final_predictions)
rmse = np.sqrt(mean_squared_error(y_test, final_predictions))

print(f"--- Model Evaluation ---")
print(f"Mean Absolute Error (MAE): {mae:.2f} positions")
print(f"Root Mean Squared Error (RMSE): {rmse:.2f} positions")

# --- STEP 6: MAKE A LIVE PREDICTION ---
# Example: Predict position for M_VERSTAPPEN (encoded) starting P3 at Silverstone (encoded)
sample_input = pd.DataFrame([{
    'season': 2026,
    'track': encoders['track'].transform(['Silverstone'])[0],
    'driver': encoders['driver'].transform(['M_VERSTAPPEN'])[0],
    'team': encoders['team'].transform(['Red Bull'])[0],
    'grid_position': 3
}])

pred_pos = model.predict(sample_input)[0]
print(f"\nPredicted finishing position for sample driver: {max(1, min(20, round(pred_pos)))}")

--- Model Evaluation ---
Mean Absolute Error (MAE): 1.55 positions
Root Mean Squared Error (RMSE): 1.86 positions

Predicted finishing position for sample driver: 4

In [2]:
import numpy as np
import pandas as pd

# 1. Setup Simulation Parameters
NUM_SIMULATIONS = 10000
LAPS = 50

# Driver profiles: [Baseline Lap Time (secs), Tire Wear per lap, DNF chance per lap]
drivers = {
    "Verstappen": {"base_pace": 85.0, "tyre_wear": 0.05, "dnf_chance": 0.001},
    "Hamilton":   {"base_pace": 85.5, "tyre_wear": 0.04, "dnf_chance": 0.001},
    "Norris":     {"base_pace": 85.2, "tyre_wear": 0.06, "dnf_chance": 0.002}
}

# Track final results across all simulations
results_log = []

print(f"🔄 Running {NUM_SIMULATIONS:,} race simulations...")

# 2. Monte Carlo Loop
for sim in range(NUM_SIMULATIONS):
    race_times = {}
    
    for driver, stats in drivers.items():
        total_time = 0.0
        has_dnf = False
        tyre_age = 0
        
        for lap in range(1, LAPS + 1):
            # Roll for DNF
            if np.random.random() < stats["dnf_chance"]:
                has_dnf = True
                break
            
            # Base lap time + degradation penalty
            lap_time = stats["base_pace"] + (tyre_age * stats["tyre_wear"])
            
            # Add normal variance (driver consistency/traffic)
            lap_time += np.random.normal(loc=0.0, scale=0.3)
            
            # Scheduled Pit Stop on Lap 25
            if lap == 25:
                # Average pit lane loss is 20s + random variance for the mechanical stop
                pit_stop_duration = 20.0 + np.random.normal(loc=2.5, scale=0.4)
                
                # 2% chance of a catastrophic pit stop error (cross-threaded nut)
                if np.random.random() < 0.02:
                    pit_stop_duration += np.random.uniform(5.0, 12.0)
                    
                lap_time += pit_stop_duration
                tyre_age = 0 # Reset tire age
            else:
                tyre_age += 1
                
            total_time += lap_time
            
        # Store final time or filter out DNFs
        race_times[driver] = total_time if not has_dnf else float('inf')
        
    # Rank the finishers for this specific trial
    sorted_finishers = sorted(race_times.items(), key=lambda x: x[1])
    
    for rank, (driver, final_time) in enumerate(sorted_finishers, start=1):
        results_log.append({
            "Simulation": sim,
            "Driver": driver,
            "Position": rank if final_time != float('inf') else "DNF"
        })

# 3. Analyze Results
df = pd.DataFrame(results_log)

# Calculate win probabilities
win_counts = df[df["Position"] == 1]["Driver"].value_counts(normalize=True) * 100
dnf_counts = df[df["Position"] == "DNF"]["Driver"].value_counts(normalize=True) * 100

print("\n🏆 Win Probability:")
for driver, prob in win_counts.items():
    print(f" - {driver}: {prob:.2f}%")

print("\n⚠️ DNF Probability:")
for driver, prob in dnf_counts.items():
    print(f" - {driver}: {prob:.2f}%")

🔄 Running 10,000 race simulations...

🏆 Win Probability:
 - Verstappen: 95.17%
 - Norris: 3.83%
 - Hamilton: 1.00%

⚠️ DNF Probability:
 - Norris: 48.36%
 - Hamilton: 26.32%
 - Verstappen: 25.32%